import Head from "next/head";
import { Inter } from "next/font/google";

import ServiceOffering from "@/components/main-page/service-offering/";
// import Carousel from "@/components/hero-carousel/";
import Contact from "@/components/main-page/contact-us";
import Layout from "@/components/Layout";
import Reviews from "@/components/main-page/review-section";
import CustomSlider from "@/components/carousel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    // const slides = [
    //     { image: "/images/carousel_images/c1.png" },
    //     { image: "/images/carousel_images/c2.png" },
    //     { image: "/images/carousel_images/c3.png" },
    // ];
    return (
        <>
            <Head>
                <title>The Wright Fence Co.</title>
                {/* TODO: Add meta tags and update website description */}
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className={`${inter.className}`}>
                    {/* <Carousel slides={slides} simpleMode={0} /> */}
                    <CustomSlider />
                    <ServiceOffering />
                    <Reviews />
                    <Contact />
                </main>
            </Layout>
        </>
    );
}
