import Head from "next/head";
import { Inter } from "next/font/google";

import ServiceOffering from "@/components/main-page/service-offering/";
import Carousel from "@/components/hero-carousel/";
import Contact from "@/components/main-page/contact-us";
import Layout from "@/components/Layout";
import Reviews from "@/components/main-page/review-section";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const slides = [{ image: "/images/fence1.jpg" }, { image: "/images/fence2.jpg" }, { image: "/images/fence3.jpg" }];
    return (
        <>
            <Head>
                <title>The Wright Fence Co.</title>
                {/* TODO: Add meta tags and update website description */}
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className={`${inter.className}`}>
                    <Carousel slides={slides} simpleMode={0} />
                    <ServiceOffering />
                    <Reviews />
                    <Contact />
                </main>
            </Layout>
        </>
    );
}
